### ISSUE TITLE
votes for answers not tallied when viewing bookmarks

### ISSUE THREAD

**Issue by nhayden** [Bioconductor/legacy.support.bioconductor.org#20]
Votes are not tallied correctly. For example, if I bookmark a question (2 votes) and an answer (4 votes) and view my bookmarks, in the bookmarks page ti will show 0 votes next to the entry for the answer, and 6 votes next to the entry for the original question. This is somewhat confusing if it's intentional, but perhaps bookmarking a question and answer is an unexpected use case.

But if I only bookmark the answer, that definitely shows an incorrect tally (0).

**Comment by dtenenba** [comment]
@ialbert this is somewhat related to what I just emailed you about (bookmarks showing up as votes); any ideas? Thanks.

**Comment by ialbert** [comment]
there is ui oversight here in the what information is shown for which post.

A post in biostar has two scores a thread score and a post score. The thread score is associated with a top level post (say a question) and represents the sum of all votes in the thread. When one looks at a post listing it is the thread score that is visible. The reason for it working this way is  that a bad question could have a really good upvoted answers and we want to be able to tell from the list of questions which post has lots of voting on posts that belong to it.

When one visits a post detail page they see the votes broken down into each post.

Now the thread score stays zero for answers and the oversight is that that interface element is the same as the one used on the main page for  top level posts. Thus it shows the thread score instead of the post score even for answers. It needs a new interface element. We are fixing most templates and simplifying the whole system hence are a little reticent in fixing this up in a push when the whole thing is slated for a redesign.

**Comment by ialbert** [comment]
The fix would go here

https://github.com/Bioconductor/support.bioconductor.org/blob/master/biostar/server/templates/server_tags/post_count_box.html#L9

but it gets a little ugly as it needs to be wrapped into a django conditional that tests `post.is_toplevel` and depending on the truth value uses `post.score` or `post.thread_score`

alas this whole piece is too complicated to begin with and just complicates things even more.

It will be fixed once we rework the templates.

**Comment by nhayden** [comment]
Ok, thanks very much for the explanation @ialbert. It's minor enough that there are plenty of other high-priority features that take precedence.
