### ISSUE TITLE
tag limits

### ISSUE THREAD

**Issue by dtenenba** [Bioconductor/legacy.support.bioconductor.org#25]
reported  by @vobencha 

Not sure if this is an upstream bug, tagging @ialbert

"If I choose a tag (say limma) then limit these messages to 'this year' 
many are outside a ~3 month window. The other limits appear to work ... 
'today', 'this week' and 'this month'. Looks like the problem is just 
with 'this year'."

**Comment by mtmorgan** [comment]
I think the filter is on 'updated' (new answers / comments), so if the question was updated in the last year, even the issue was created ten years ago, the issue shows up. There are always 86 pages of results. Here's the [last page](https://support.bioconductor.org/?page=86&sort=New%20answers&limit=This%20year) sorted by 'New answers', and the oldest 'new answer' is 12 months ago.

**Comment by ialbert** [comment]
yes as @mtmorgan points out, the time limits apply to activity (last update). 

The last updated field for top level posts tracks activity in the entire thread.
