### ISSUE TITLE
Support markdown syntax

### ISSUE THREAD

**Issue by lgatto** [Bioconductor/legacy.support.bioconductor.org#5]
when writing posts would be really great.

**Comment by dtenenba** [comment]
This has come up before. Apparently biostar (the software our site is based on) used to use a markdown-based editor (the same one used by stackoverflow if I am now mistaken) but now uses the one you see on our site. 

It might be possible to dig through the git commits and pull out the relevant ones and reintroduce that editor. I have some concerns about that: one, that users who prefer a more WYSIWYG editor will be unhappy, and two that we'll be diverging uncomfortably far from the biostar master branch. I wonder if @ialbert might be interested in adding support for using multiple editors, which the user could change, either on demand or in their profile.

**Comment by lgatto** [comment]
> I have some concerns about that: one, that users who prefer a more WYSIWYG editor will 
> be unhappy, and two that we'll be diverging uncomfortably far from the biostar master 
> branch.

Yes, I understand. I just _expected_ the editor to support markdown from using SO, github (and Biostar some time ago, I believe) and hoped the right button, that says source, could let me select markdown.

**Comment by ialbert** [comment]
Supporting different editors is a fairly straightforward task - but it is
not necessarily a quick fix that could be done in a day or so.

One needs to add a new field to the user profiles to keep track of the
option, load a different editor on the post edit page and into the answer
box. Finally ensure that the markdown is processed only when the markdown
option is set.

Then one needs to write tests etc.

Due to the way my schedule works I have little time to develop new features
during the Fall (2014) but I can see this being implemented starting mid
January 2015.

best,

**Comment by lgatto** [comment]
If you ever  get the chance, thank you in advance.

**Comment by khughitt** [comment]
:+1:

**Comment by schifferl** [comment]
I can't close the issue myself but this was added with c1110eb. The issue can now be closed.

**Comment by dtenenba** [comment]
I still don't see the button unless I clear my cache. Did we add (or modify) a query string when sourcing the js file, to tell the browser that the contents have changed? Not sure this should be closed if the feature is not visible to most users.

**Comment by lgatto** [comment]
It seems to work for answers, but not for comments. I haven't had a chance to test it with a question.
