### ISSUE TITLE
notifications mode changes

### ISSUE THREAD

**Issue by dtenenba** [Bioconductor/legacy.support.bioconductor.org#9]
I set my Notifications mode to "email for every new thread". A few days later I noticed I wasn't getting emails from the site. I went to my profile page and my notifications setting was "local messages". I changed it back to "email for every new thread". Then the same thing happened again! 
The setting is apparently not persistent?

**Comment by dtenenba** [comment]
Also my biography was lost. Not sure if this is related.

**Comment by dtenenba** [comment]
@ialbert Can you have a look at this? It happened again. I wonder if some daily celery job got rid of my notification preference? Note that we renamed 'mailing list mode' to 'email for every new thread' because we did not want to give the impression that it would function just like our old mailing list. Thanks.

**Comment by ialbert** [comment]
did anyone else report this? 

Losing autobiography and email settings make sense to originate from the same source, it seems to be resetting the user profile. 

In the past I have never had autobiography loss ever reported.

**Comment by dtenenba** [comment]
Nobody else has reported it but others could be experiencing it without reporting it, I suppose. Thanks.

**Comment by ialbert** [comment]
I've added the same settings to my account to try to reproduce it.

**Comment by dtenenba** [comment]
Hi again @ialbert ,

It's still happening. Looking in the celery log I see this:

[2014-09-25 11:49:06,574: INFO/Worker-2] biostar.awards.create_user_award[bcf5d9bb-c3b1-43a7-a1c0-8076be7d10fd]: award check for Dan Tenenbaum: dtenenba@fhcrc.org (4256)
[2014-09-25 11:49:06,581: INFO/Worker-1] biostar.awards.check_user_profile[9d443d57-dccf-4d43-8631-3487627c4357]: profile check from 140.107.151.151 on Dan Tenenbaum: dtenenba@fhcrc.org (4256)

I also see that awards.py does change users' profiles (line 47). Could that be the culprit?

Is there a way I can run awards.py from the command line or console? Then I could see exactly what it does.

Thanks,
Dan

**Comment by ialbert** [comment]
It is pretty strange. I have also set up the same email on every thread and my autobiography and so far both are the same as I set them.

The line you refer to only touches the location and it will only get executed if your location it is not set so it is hard to see how that changes the autobiography. 

can you look in the server access logs to recent hits to 

/u/edit/4256/

this would only trigger for user edit via the web.

What else runs as cron or celery?

**Comment by ialbert** [comment]
as for triggering the award check, if you log out and log back in the award check celery job will run. It also runs periodically every ten minutes (as long as the user is active on the site) as set in the settings:

SESSION_UPDATE_SECONDS = 10 \* 60

**Comment by dtenenba** [comment]
I logged out and back in and my mailing list settings were the same.

Nobody else has reported this problem so it might just be something with me.

I didn't find `/u/edit/4256/` in the celery log.

In celery the following jobs run:

prune_data
sitemap
update_index
awards
hourly_dump
daily_dump
hourly_feed
daily_feed
(bump is not run)

In crontab there are "@reboot" tasks that start the celery worker and beat, and then there is the clean_session.sh script that you suggested I run. There's another job that just rsync's database backups to another machine for recovery if the main machine goes down.

I think that my notifications settings last longer than 1 hour. So maybe it's a different job that affects it. It seems to be more like every 24 hours. Today it happened sometime between early and late morning Seattle time.

**Comment by dtenenba** [comment]
Aha, here it is:

```
[2014-09-25 11:37:17,382: INFO/MainProcess] Task biostar.awards.create_user_award[bf0f6374-cc8c-4535-8935-2f813f05a21d] succeeded in 0.183899186552s: None
[2014-09-25 11:37:17,432: DEBUG/Worker-2] (0.021) UPDATE "users_profile" SET "user_id" = 4256, "uuid" = 'c31beeac355187dcb9d13fc487ff47b0', "last_login" = '2014-09-24 20:20:25.493635+00:00', "date_joined" = '2010-09-13 08:54:06+00:00', "location" = 'United States', "website" = '', "scholar" = '', "twitter_id" = '', "my_tags" = '', "info" = '', "message_prefs" = 0, "flag" = 0, "watched_tags" = '' WHERE "users_profile"."id" = 4256 ; args=(4256, u'c31beeac355187dcb9d13fc487ff47b0', u'2014-09-24 20:20:25.493635+00:00', u'2010-09-13 08:54:06+00:00', u'United States', u'', u'', u'', u'', u'', 0, 0, u'', 4256)
```

It is the awards task. Notice how it set message_prefs to 0 when I had it set to 4.

Any idea how to fix it?
Thanks,
Dan

**Comment by ialbert** [comment]
interesting and is getting more mysterious, alas it still not clear how
exactly this happens

that is because the function only  triggers the codepath that you list if the
location is missing, and then it updates the location and saves the user.
What this means is that the user is already an empty user when it got into the
create_award function().

When the save takes place it re-saves all attributes and doesn't just
update the single one has changed, in the log it may look like it is overwriting the 
information but it is not. But only field that was changed was the location.  What 
is really curious that the last_login date says `2014-09-24 20:20:25.493635+00:00` 
what this means is that it thinks it was last night' but the rest of the line says that it is
today.

The user information comes from the celery queue. The way this works is
that server pushes a function call and serialized user data onto the celery
queue. The worker, in a completely separate python process, pulls the 
function name and the parameter data and gets to work.

hmmm, here is a thought

It is almost as if there was another webserver that ran in parallel and
every once in a while sent commands to the same celery queue the main
database uses. Because on the other side the celery worker does not know
who sent the command and executes it directly but it will write to the
database it knows about that could be different from the database the
original user information came from.

Is it possible that the test server writes to the same queue, and then any
time you log into the test server it sends a job to the queue that executes
on the main server?

First what celery queue are you using?

**Comment by dtenenba** [comment]
Aha...that's it. More details later....
Dan

**Comment by dtenenba** [comment]
OK, so we have a staging server and we also have a few people with their own local instances so that they can develop and test. Up until today, they all had the line 

```
BROKER_URL = 'amqp://guest:guest@habu:5672//'
```

In celeryconfig.py. habu is the machine where the production server runs. 

So I guess that is what caused the problem. 

I changed this to

```
import socket
if (socket.gethostname() == "habu"):
    BROKER_URL = 'amqp://guest:guest@habu:5672//'
else:
    BROKER_URL = 'amqp://guest:guest@localhost:5672//'
```

This causes stack traces on machines other than habu, but I don't really care, because I only want to run celery tasks on that one machine.

Thanks for helping me track this down.
